### ISSUE TITLE
Why DO NOT MODIFY mod?

### ISSUE THREAD

**Issue by LionZXY** [JLChnToZ/MCCustomSkinLoader#50]
Hello. I adapt your mod for my skin system, but when i build mod, i recieve crash:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CustomSkinLoader (customskinloader)
Caused by: java.lang.RuntimeException: Fingerprint ERROR, please **DO NOT MODIFY** any mod.
```

Why are you against mod mods?

**Comment by LionZXY** [comment]
My modification replace mojang api hosturl for my implementation.

**Comment by xfl03** [comment]
You can simply remove this line in code and compile it.
Then please upload the source which get changed.
@LionZXY

Someone download the jar and modify constant string in class files to change the url, the validation is just for them, because GPLv3 require to open source after modification, they cannot.
